{{- /*
  ExternalSecret for Harbor DB credentials. Uses the same 1Password item as the Postgres cluster
  (postgresql / password). Creates secret harbor-db with key "password" (Harbor chart expects this key).
  Requires externalSecrets.db.enabled and ClusterSecretStore (e.g. onepassword-connect).
*/ -}}
{{- if .Values.externalSecrets.db.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.db.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.db.secretStoreRef.name | default "onepassword-connect" }}
    kind: {{ .Values.externalSecrets.db.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: harbor-db
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        # Harbor chart reads password from secret; we inject username via core.extraEnvVars so both come from secret.
        username: {{ "postgres" | b64enc }}
        password: {{ quote (printf "{{ .%s }}" "password") }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.db.itemTitle | default "postgresql" | quote }}
        property: {{ .Values.externalSecrets.db.passwordProperty | default "password" | quote }}
{{- end }}
